name: Gradle Build & K8S Deploy
# V를 앞글자로 가지는 태그가 push 될 때 해당 workflow 실행 - ex) V2, V3
on:
  push:
    tags: V*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Grant execute permission for gradlew
      run : chmod +x gradlew
      
    - name: Build with jib
      run: |
        ./gradlew jib \
        -Djib.to.image="zxcvb5434/devopstest:${GITHUB_REF##*/}"
        
  deploy:
    
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: update yaml file
      run: |
        sed -i s/latest/${GITHUB_REF##*/}/ ./k8s/deployment.yaml
        cat ./k8s/deployment.yaml
    
    - name: Kubectl apply
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: ${{ secrets.KUBECONFIG }}
        command: apply -f ./k8s/deployment.yaml
